---
title: "DPLYR Skill Share"
author: "CFerri"
date: "October 27, 2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(dplyr)
library(ggplot2)

```


#Quick look at dataframes

```{r pressure, echo=FALSE, fig.cap="A caption", out.width = '100%'}
```


#Filter
```{r}
mpg
head(mpg)
str(mpg)
dim(mpg)
names(mpg)
```
```{r}
hist(mpg$cty)
filter(mpg, cty > 25)
filter(mpg, cty > 25 & model == "civic")
```


#Select
```{r}
select(mpg, manufacturer)
names(mpg)
##Concatenate columns to select from df
mpg %>% 
  select(c(7, 8)) %>% 
  arrange(cty)
```

#Pipe
```{r}
mpg %>% 
  filter(cty > 25) %>% 
  select(c(7,8))

names(mpg)
##What cars get the worst mpg?
mpg %>% 
  select(c(2,8)) %>% 
  filter(cty < 15)
  
mpg %>% 
  filter(cty < 15) %>% 
  select(2)
  
```

#Group By
```{r}
names(mpg)
drv_count <- n
mpg %>% 
  group_by(drv) 
 
```

#Summarise
```{r}
mpg %>% 
  group_by(drv) %>% 
  summarise(drv_count = drv_count(), avgcity = mean(cty, na.rm = T))
```



#Mutate
```{r}
mpg %>% 
  group_by(drv) %>% 
  summarise(drv_count = drv_count(), avgcity = mean(cty, na.rm = T)) %>% 
  mutate(test = drv_count * avgcity)



```


#Arrange
```{r}
mpg %>% 
  mutate(conversion = displ * .16) %>% 
  arrange(desc(cty))
```

##What is the jettas avg cty mpg?
```{r}
jetta_list <- filter(mpg, model == "jetta")
jetta_list
jetta_avg_cty <- sum(jetta_list$cty)/9
jetta_avg_cty

```
##What year produced the best mpg(cty)?
```{r}
year_df <- mpg %>% 
  select(year, cty) %>% 
  arrange(year)
year_df
ninetynine_df <- mpg[mpg$year == 1999, c(4,8)]
ninetynine_df  
avg_cty_mpg_ninetynine <- sum(ninetynine_df$cty)/117
avg_cty_mpg_ninetynine
##Insight, data frame is composed of vehicles only from 1999 and 2008
twothoueight_df <- mpg[mpg$year == 2008, c(4,8)]
twothoueight_df  
avg_cty_mpg_twothoueight <- sum(twothoueight_df$cty)/117
avg_cty_mpg_twothoueight

avg_cty_mpg_ninetynine > avg_cty_mpg_twothoueight
##2008 Produced a better mpg avg than 1998
##This can suggest that more efficient vehicles were created in between the years used in this data frame 1999 to 2008
```
